### ISSUE TITLE
Dropdown menu broken on Firefox Developer Edition

### ISSUE THREAD

**Issue by michallepicki** [horst3180/arc-firefox-theme#83] opened 2016-09-03 12:58 UTC
I am on Firefox Developer Edition 50.0a2.
Dropdown menu is messed up and its buttons are not working. See screenshot.
![arc theme bug firefox developer edition](https://cloud.githubusercontent.com/assets/4972756/18224936/e5a4756a-71e6-11e6-85b5-ebf7c427b31d.png)

**Comment by stonehellway** [comment] 2016-09-03 18:04
Same issue. I use the same Firefox version. Every Firefox theme is impacted.
I use the theme version 48.20160802.
Tried a fresh install of Firefox Developer edition: Same issue on Fedora 24 (xfce) and Windows 10.

![firefox developer](https://cloud.githubusercontent.com/assets/15817017/18226781/7bc73170-7211-11e6-80e7-e84443fc613d.png)

**Comment by raku-cat** [comment] 2016-09-05 09:01
Can also confirm, I'm on aurora though
Edit: The offending file is arc-firefox-theme/chrome/browser/customizeableui/panelUIOverlay.css if anyone wants to mess with it, I will be trying to fix it if I can.
Edit2: Noticed this also happens with ublock

**Comment by horst3180** [comment] 2016-09-19 15:59
Duplicate of https://github.com/horst3180/arc-firefox-theme/issues/74

**Closed as completed by horst3180** 2016-09-19 15:59 UTC
